export enum ContextValue {
  Repository = "repository",
  Changes = "changedFile",
  StagedChanges = "stagedFile",
  LocalBranches = "localBranches",
  LocalBranchesCurrent = "localBranches.current",
  RemoteBranches = "remoteBranches",
  Branch = "branch",
  File = "file",
  Stash = "stash",
  Commit = "commit",
  LocalBranchesSection = "localBranchesSection",
  RemoteBranchesSection = "remoteBranchesSection",
  ChangesSection = "changesSection",
  StagedChangesSection = "stagedChangesSection",
  StagedChangesSectionEmpty = "stagedChangesSectionEmpty",
  TagsSection = "tagsSection",
  StashSection = "stashSection",
}
