export const COMMANDS = {
  REFRESH: "gops.refresh",
  CHECKOUT_BRANCH: "gops.checkout",
  CHECKOUT_REMOTE_BRANCH: "gops.checkoutRemoteBranch",
  DELETE_BRANCH: "gops.deleteBranch",
  RENAME_BRANCH: "gops.renameBranch",
  PUSH: "gops.push",
  PULL: "gops.pull",
  CREATE_BRANCH_FROM_CURRENT: "gops.branch.current",
  CREATE_BRANCH: "gops.branch",
  CREATE_TAG: "gops.tag",
  SHOW_DIFF: "gops.showDiff",
  STAGE_FILE: "gops.stageFile",
  STAGE_ALL_FILES: "gops.stageAllFiles",
  DISCARD_FILE: "gops.discardFile",
  DISCARD_ALL_FILES: "gops.discardAllFiles",
  UNSTAGE_FILE: "gops.unstageFile",
  UNSTAGE_ALL_FILES: "gops.unstageAllFiles",
  COMMIT: "gops.commit",
  SHOW_GIT_GRAPH: "gops.showGitGraph",
  PUBLISH_BRANCH: "gops.publishBranch",
  FETCH: "gops.fetch",
  POP_STASH: "gops.popStash",
  STASH_CHANGES: "gops.stashChanges",
} as const;
